src/blas/BLASBenchmarks.jl
src/lapack/LAPACKBenchmarks.jl

`eig` for special matrix types and a bunch of BLAS.

Added more benchmarks for linear algebra

---

README.md

I thought some cookbook material might be helpful for folks who run this rarely. If the material is too long for the README, I'm happy to have you put it in a separate file linked to the README.
Also, one of the things this highlights is perhaps providing a way of formatting the output to make it easier to re-run one of the regressing benchmarks.

Add "recipes" for running and analyzing benchmarks locally

---

src/scalar/ScalarBenchmarks.jl

This is a companion to https://github.com/JuliaLang/julia/pull/16687.
Please feel free to suggest better tags.

Test performance of "iteration" over numbers

---

README.md

@timholy Sorry, I meant to mention these edits in the PR review for #12, but I was too busy at the time and the PR ended up slipping my mind.

edit recipe in README

---

src/linalg/LinAlgBenchmarks.jl

Thanks for finding this @MatthiasJReisinger! Since I couldn't reproduce this problem locally, would you mind checking to see if this fixes the issue on your end?

fix potential nonsymmetry of cholfact benchmark input

---

src/array/ArrayBenchmarks.jl

Ref https://github.com/JuliaLang/julia/pull/18269
Master:
```julia
julia> run(BaseBenchmarks.SUITE["array"]["index"][("sumcartesian","SubArray{Float64,3,Array{Float64,3},Tuple{UnitRange{Int64},UnitRange{Int64},UnitRange{Int64}},false}")])
BenchmarkTools.Trial: 
samples:          10000
evals/sample:     1
time tolerance:   40.00%
memory tolerance: 1.00%
memory estimate:  608.00 bytes
allocs estimate:  23
minimum time:     5.72 μs (0.00% GC)
median time:      5.80 μs (0.00% GC)
mean time:        8.08 μs (0.00% GC)
maximum time:     22.23 ms (0.00% GC)
julia> run(BaseBenchmarks.SUITE[["array","index",("sum","3darray")]])
BenchmarkTools.Trial: 
samples:          10000
evals/sample:     1
time tolerance:   40.00%
memory tolerance: 1.00%
memory estimate:  0.00 bytes
allocs estimate:  0
minimum …
```

Add 3d Array and SubArray benchmarks

---

src/BaseBenchmarks.jl

Ref https://github.com/JuliaCI/BaseBenchmarks.jl/pull/24#issuecomment-247633004

Check that module entry exists in params.jld before trying to load it

---

src/nullable/NullableBenchmarks.jl

In current Julia master, this benchmark is slow since it needs
to compute !hasvalue. Better reflect the new structure of Nullable.
Also avoid using the two-argument Nullable() constructor so that
the code works on all Julia versions.

Update Nullable benchmarks to reflect isnull -> hasvalue change

---

src/BaseBenchmarks.jl
src/dates/DatesBenchmarks.jl

Add Dates benchmarks

---

REQUIRE
src/problem/GoGame.jl

ref [today's daily build](https://github.com/JuliaLang/julia/commit/80770e955906c8cdbcfaf2ea73ed772195429aad#commitcomment-19824380) and  JuliaLang/julia@2751493abfae6ffe6b833b06c7950887a9379fbc

backwards compatible fix for recent xor change in Base

---

src/array/ArrayBenchmarks.jl
src/array/generate_kernel.jl
src/array/generate_loops.jl
src/array/indexing.jl

This is my first stab at adding a performance test for JuliaLang/julia#18774, using a 6 dimensional array.  I have a script that auto generates these functions, so I can create as high dimension cases as you want.  I haven't created a benchmark before, so let me know if I need to make any changes.

add 6d indexing [WIP]

---

src/scalar/ScalarBenchmarks.jl

Currently only exponent functions, mostly @musm's recent PRs in Base.

Add Math benchmarks category

---

src/dates/DatesBenchmarks.jl

Additional benchmarks for DateTime parsing which were useful in the development of https://github.com/JuliaLang/julia/pull/19519

Add more DateTime parsing benchmarks

---

src/shootout/revcomp.jl

ref https://github.com/JuliaLang/julia/pull/19449

do not access String .data field

---

src/scalar/ScalarBenchmarks.jl

May need latest BenchmarkTools to get more meaningful timings on nanosoldier?

Add exp benchmarks

---

REQUIRE

Ref https://github.com/JuliaLang/julia/pull/20993#issuecomment-292483918

bump compat req

---

src/scalar/ScalarBenchmarks.jl

Add benchmarks for exp10 function

---

.travis.yml
appveyor.yml
src/sparse/SparseBenchmarks.jl

Ref https://github.com/JuliaLang/julia/pull/22175

Add sparse benchmarks for AbstractUnitRange

---

src/scalar/ScalarBenchmarks.jl

Unswitch + and *

---

src/misc/MiscellaneousBenchmarks.jl

Inspired by JuliaLang/julia#22089

added some julia parser etc benchmarks

---

src/problem/ChaosGame.jl
src/problem/ProblemBenchmarks.jl

Creates funny images like:
Translated from https://github.com/python/performance/blob/master/performance/benchmarks/bm_chaos.py.

add chaos game fractal benchmark problem

---

src/linalg/LinAlgBenchmarks.jl
src/problem/ChaosGame.jl
src/problem/ProblemBenchmarks.jl
src/scalar/ScalarBenchmarks.jl

Offer master to the Nanosoldier

---

src/scalar/ScalarBenchmarks.jl

(cherry picked from commit 5ad2429f80b84949f8ef47ad15b5a602f7f4af5f)

Change |x| to abs(x) (#97)

---

src/scalar/ScalarBenchmarks.jl

Add atan benchmarks.

---

src/sparse/SparseBenchmarks.jl

xref https://github.com/JuliaLang/julia/pull/23536

add some benchmarks for sparse matrix construction

---

src/scalar/ScalarBenchmarks.jl

These benchmarks hit all branches of atan2 (unless you're in the case where atan is called, atan benchmarks take care of that). Is this over the top, or good?

atan2 benchmarks

---

src/random/RandomBenchmarks.jl

This fixes part of #124. E.g. When wanting to benchmark
`rand(Int)` and `rand(UInt)`, the following loop won't
measure what is expected:
`for T=(Int, UInt); @benchmarkable rand($T); end`
In order to benchmark the equivalent of
`@benchmarkable rand(Int); @benchmarkable rand(UInt)`,
we "value-fy" the types with `Val`.

random: don't benchmark functions with interpolated types

---

README.md

Cf. https://github.com/JuliaCI/BaseBenchmarks.jl/pull/132/files#r151877840.

update README with a correct way of loading .json files

---

REQUIRE
src/dates/DatesBenchmarks.jl
src/misc/MiscellaneousBenchmarks.jl

Currently causing errors in the Dates tests.

Fix for Dates moving to stdlib

---

src/array/subarray.jl
src/micro/methods.jl
src/misc/MiscellaneousBenchmarks.jl
src/scalar/ScalarBenchmarks.jl
src/shootout/revcomp.jl

Checks off a couple more from #158.

Fix a few more 0.7 deprecations

---

src/micro/methods.jl
src/sparse/SparseBenchmarks.jl

Ref #158
@Sacha0 Does this look right?

Rewrite .' calls to use transpose

---

src/string/StringBenchmarks.jl

@nalimilan Does this look right?

Fix search/searchindex deprecations

---

src/scalar/ScalarBenchmarks.jl

ref: 
https://github.com/JuliaLang/julia/pull/24859
https://github.com/JuliaLang/julia/pull/25903
https://github.com/JuliaLang/julia/pull/25948

exp2, expm1, cbrt benchmarks.

---

src/find/FindBenchmarks.jl

since generators are not indexable

findall no longer supports generators

---

src/array/ArrayBenchmarks.jl
src/linalg/LinAlgBenchmarks.jl

Should fix JuliaLang/julia#26898 (but done blind).

Fix overflow on cumsum! test

---

src/array/ArrayBenchmarks.jl

This allows the tuning script to go through, at least.

Fix for var moving to StatsBase

---

src/union/UnionBenchmarks.jl

These are the most straightforward ways of writing such loops, so they should be fast.

Add more benchmarks for sum with Union{T,Nothing}

---

src/misc/MiscellaneousBenchmarks.jl

likely responsible for some of the parse regressions in https://github.com/JuliaLang/julia/pull/27030

fix deprecation warnings with assert()

---

src/misc/MiscellaneousBenchmarks.jl

Reverts JuliaCI/BaseBenchmarks.jl#234

Revert "WIP: Benchmark flatten"

---

src/misc/MiscellaneousBenchmarks.jl

Addresses @jrevels comments in #234

Benchmark flatten

---

src/array/ArrayBenchmarks.jl
src/array/sumindex.jl

xref https://github.com/JuliaLang/julia/pull/37230 and https://github.com/JuliaLang/julia/pull/37277

Test indexing performance of ReinterpretArrays

---

src/union/UnionBenchmarks.jl

Covers https://github.com/JuliaLang/julia/pull/30480.

Add benchmark for collect with Union eltype

---

src/tuple/TupleBenchmarks.jl

from julia issue: https://github.com/JuliaLang/julia/pull/31160

add benchmark for converting to long tuple types

---

src/BaseBenchmarks.jl
src/frontend/FrontendBenchmarks.jl

for https://github.com/JuliaLang/julia/pull/43022

add benchmark for resolve-scopes

---

README.md

Fixed dead link (Issue #289)

---

src/inference/InferenceBenchmarks.jl

update to https://github.com/JuliaLang/julia/pull/43973

---

src/inference/InferenceBenchmarks.jl

Also renames some benchmark targets to clarify their purpose.

inference: add benchmark target for JuliaLang/julia#46729

---

src/inference/InferenceBenchmarks.jl

It turns out that the previous call signature `many_method_matches(::Float64)` was just wrong and so the benchmark hasn't been functional, especially when benchmarking the performance of optimization passes (since the preparatory abstract interpretation was not really successful).
Fixed it up, and also sets up an assertion that checks that the inference runs on each benchmarks as expected, in order to avoid this sort of problems.

inference: fixup `many_method_matches` benchmark

---

src/BaseBenchmarks.jl

necessary after https://github.com/JuliaLang/julia/pull/57133

adapt SUITE loading to const binding changes
