JuliaCI/BaseBenchmarks.jl

src/BaseBenchmarks.jl, src/tuples/TupleBenchmarks.jl
Benchmarks perfomance regression in https://github.com/JuliaLang/julia/issues/15277 / https://github.com/JuliaLang/julia/issues/15274
=> add tuple sum benchmarks

src/arrays/ArrayBenchmarks.jl, src/arrays/sumindex.jl
Ref https://github.com/JuliaLang/julia/pull/16078
The tests didn't run successfully for me:
```jl
julia> Pkg.test("BaseBenchmarks")
INFO: Testing BaseBenchmarks
ERROR: LoadError: LoadError: LoadError: LoadError: UndefVarError: ExecutionResults not defined
in include(::ASCIIString) at ./boot.jl:233
in include_from_node1(::ASCIIString) at ./loading.jl:426
in include(::ASCIIString) at ./boot.jl:233
in include_from_node1(::ASCIIString) at ./loading.jl:426
in eval(::Module, ::Any) at ./boot.jl:236
[inlined code] from ./sysimg.jl:11
in require(::Symbol) at ./loading.jl:357
in include(::ASCIIString) at ./boot.jl:233
in include_from_node1(::ASCIIString) at ./loading.jl:426
in eval(::Module, ::Any) at ./boot.jl:236
[inlined code] from ./sysimg.jl:11
in require(::Symbol) at ./loading.jl:357
in …
```
=> Add range indexing test (with boundschecking)

src/linalg/LinAlgBenchmarks.jl
In JuliaLang/julia#14722, I fixed an issue where the inner loop was type-unstable. This benchmark ensures that doesn't regress.
=> Add benchmark for A_mul_B! with different input and output types

src/array/sumindex.jl
Our inlining and codegen are getting so dang awesome on julia 0.5 that recently LLVM has begun to notice that it can skip the `div` when performing linear indexing `ArrayLS` and `ArrayLSLS`. Since testing that is not really the intention of these tests, I modified the tests to defeat it. Ref https://github.com/JuliaLang/julia/pull/17355#issuecomment-231748251.
=> Ensure that ArrayLS and ArrayLSLS really are LinearSlow

src/io/IOBenchmarks.jl
Adds benchmarks of `serialize` and `deserialize` (JuliaLang/julia#7893 and JuliaLang/julia#18633).
=> serialization benchmarks

src/BaseBenchmarks.jl, src/broadcast/BroadcastBenchmarks.jl
This adds a new suite (`broadcast`) of benchmarks testing the new broadcast-fusion functionality, the upcoming dot-operator=broadcast change, and broadcast on sparse vectors, for JuliaLang/julia#16285.
=> Broadcast benchmarks

src/array/ArrayBenchmarks.jl
Benchmarks several `reduce`-like functions to make sure we don't get regressions in this basic functionality.
=> add some reduction benchmarks to array suite

src/array/ArrayBenchmarks.jl
Add `convert` benchmarks based on JuliaLang/julia#18954
=> add convert benchmarks

src/io/IOBenchmarks.jl, test/runtests.jl
Additionally, alter the test command to ensure this case is accounted for.
=> Fix benchmark that needed state reset for every evaluation instead of every sample

src/sparse/SparseBenchmarks.jl
This pull request adds benchmarks for sparse unary minus as discussed in https://github.com/JuliaLang/julia/pull/19530. Apologies in advance for inevitable BaseBenchmarks.jl-newbie errors. Thanks and best!
=> Add benchmarks for sparse unary minus

src/shootout/nbody_vec.jl
A more "modern" version of nbody_vec using dot operators and fusion (in 0.6).   Also, `sum(x .^ 2)` should really be `sumabs2(x)` in performance-sensitive code.
=> modern vectorization of nbody_vec

src/problem/MonteCarlo.jl
use the new-style "dot-vectorized" operators in the Monte-Carlo test in order to take advantage of JuliaLang/julia#17623, since presumably this will be the preferred style of vectorized code in performance-sensitive situations going forward.
Also, the "de-vectorized" version shouldn't allocate a temporary array for `randn()`, since that is how you would realistically want to write the optimized devec code.
=> better vectorization of monte-carlo test

src/broadcast/BroadcastBenchmarks.jl, src/problem/Laplacian.jl, src/shootout/nbody_vec.jl, src/utils/CompatUtils.jl
This updates the laplace benchmark to use fused dotops in the vectorized versions as discussed in JuliaLang/julia#1168
=> update laplace benchmark to use fused dotops

src/linalg/LinAlgBenchmarks.jl
Hopefully will allow the benchmarks to run on my branch. Should be backwards compatible.
=> fix accessing T.name for jb/subtype

src/array/.gitignore
commit message:
> The file src/array/hdindexing.jl is generated dynamically by
> ArrayBenchmarks.jl when the array benchmarks are executed. This
> caused git status to be dirty.
> 
> This commit adds a src/array/.gitignore which explicitly ignores
> that file.
When playing around with this package (as you do), I noticed that the array benchmarks generate a file called `hdindexing.jl` here: https://github.com/JuliaCI/BaseBenchmarks.jl/blob/master/src/array/ArrayBenchmarks.jl#L89-L90
Executing just the `"array"` benchmarks or `Pkg.test` cause a dirty git, since it is not deleted after the benchmarks were run. A entry in `.gitignore` seems like an easy band-aid.
=> array benchmarks causes dirty git

src/linalg/LinAlgBenchmarks.jl
Start benchmarking `sqrtm`, cf. https://github.com/JuliaLang/julia/pull/20214
Add `UnitUpperTriangular` and `NPDUpperTriangular` (NPD = non-positive-definite) matrices to the testing
=> RFC add matrix types, add sqrtm benchmarks

src/array/ArrayBenchmarks.jl, src/array/subarray.jl
...instead of running `perf_lucompletepivCopy!` twice.
Ref https://github.com/JuliaCI/BaseBenchmarks.jl/commit/da9fda347309e3ee47437cfa2e249171109bf79f#commitcomment-20858355
=> Actually run `perf_lucompletepivSub!`

src/linalg/LinAlgBenchmarks.jl
The one that needs this the most is `sqrtm`. It's been really noisy lately, so I looked into why. It turns out it takes a full second for a single execution, so it was only being executed once before hitting the default time budget. I bet this is also the case for a couple of other noisy benchmarks. I'll look at the sparse benchmarks as well, and potentially make the same change there.
It's easy to tune the time budget per benchmark/group, so we should really start doing so if we're going to add long-running benchmarks. I should also start checking for this when reviewing new BaseBenchmarks PRs. We can also raise the default time budget and lower the sample ceiling (`10000` is probably overkill for most benchmarks).
=> increase time budget for linalg benchmarks so that more samples can be collected

src/tuple/TupleBenchmarks.jl
Add Benchmarks for a small fixed size array (FSA) implementation (based on tuples) with some reduce functionality and mat * mat/vect. 
I feel this is good to have here since we tuples are the de facto way that FSA's are implemented.
I borrowed some of your linear algebra code @andyferris. Hope you don't mind.
=> add benchmarks for fixed size arrays

src/linalg/LinAlgBenchmarks.jl, src/sparse/SparseBenchmarks.jl
Ref https://github.com/JuliaLang/julia/pull/21165
=> Benchmark for backsolve of sparse hermitian matrices

src/scalar/ScalarBenchmarks.jl
WIP as I'm not familiar at all with the framework. @tkelman [asked me](https://github.com/JuliaLang/julia/pull/21231#issuecomment-290355981) if benchmarks exist for those function, here they are. I'm not sure about pretty much everything:
1. the `tol` parameter, which I copied verbatim from other benchmarks;
2. the name "intfuncs" of the group (after the base/intfuncs.jl file where the functions are defined), and the choice of the "scalar" group;
3. the name of `tstr` containing a sign (e.g. "BigInt +") (the perfs depend on the sign of the argument);
4. whether to test multiple values, to get a sort of average, instead of only one value.
=> add prevpow2 and nextpow2 benchmarks

src/array/ArrayBenchmarks.jl, src/array/sumindex.jl
Cf. https://github.com/JuliaLang/julia/issues/20517:
`mapreduce` can be much slower than the equivalent `for`-loop, currently mostly coming from an inference bug https://github.com/JuliaLang/julia/issues/15276 related to `Core.box`.
This benchmark would allow keeping an eye on this realistic code pattern. If that is what you had in mind, @stevengj ?
=> bench mapreduce with array accesses

src/scalar/ScalarBenchmarks.jl
The benchmarks added in #81 used |x| in the descriptions to denote the absolute value of x, but that conflicts with Markdown table syntax. Thus this PR changes |x| to abs(x).
=> Fix scalar benchmarks table formatting

REQUIRE, src/array/sumindex.jl
Needed to test performance of https://github.com/JuliaLang/julia/pull/21750.
=> Remove dependence on partial linear indexing

src/linalg/LinAlgBenchmarks.jl
update `sqrtm` deprecation, add some benchmarks for `log` and `exp`
=> sqrtm -> sqrt

src/string/StringBenchmarks.jl
See https://github.com/JuliaLang/julia/pull/20621
=> Add readuntil benchmarks

src/sparse/SparseBenchmarks.jl
This pull request adds benchmarks for mixed sparse-dense matrix multiplication (in anticipation of improved kernels for these operations).
@pevnak, could you confirm that these benchmarks cover all cases relevant to your application?
These benchmarks might be a bit heavy. If so, is there some flag behind which we can hide some of these benchmarks? If not, perhaps changing the `1` in `    m, k, n = 1 .* (om, ok, on)` to `3` would more realistically exercise cache. (Edit: These benchmarks should become _much_ lighter once improved kernels go live.)
Thanks and best!
=> mixed sparse-dense matrix multiplication benchmarks

src/sparse/SparseBenchmarks.jl
Should make the sparse matmul benchmarks less noisy cc @Sacha0
=> seed random matrices for sparse matmul benchmarks

src/array/ArrayBenchmarks.jl
Good to have in general, but particularly needed before adapting these functions to support three-valued logic with missing values.
=> Add benchmarks for ==, isequal, any and all

src/BaseBenchmarks.jl, src/array/ArrayBenchmarks.jl, src/find/FindBenchmarks.jl
Use a separate file since more benchmarks should be added for other
methods, and on various types.
Will be useful to assess the impact of https://github.com/JuliaLang/julia/pull/24774.
=> Add find benchmarks

src/BaseBenchmarks.jl, src/collection/CollectionBenchmarks.jl
Maybe not everything here makes sense (so cc-ing @JeffBezanson who may have suggestions), I will review again by tomorrow. Also using `setup` with mutable benchmarks is still a bit tricky for me, I'm not sure to have got it right.
=>  add benchmarks for some collection operations

src/BaseBenchmarks.jl, src/collection/CollectionBenchmarks.jl
~DO NOT MERGE~
This is the same as #109, just to check if it can pass CI (it causes problem with tuning).
=> add benchmarks for some collection operations

src/array/sumindex.jl
This allows at least to run the tests! `ind2sub` was necessary to change (insufficient deprecation system, or oversight? may be worth to point to the author of corresponding Julia PR). For `sub2ind`, my guess is that the deprecation made the benchmark so slow that it appeared to take forevever.
=> band-aid for ind2sub & sub2ind

REQUIRE, src/problem/SparseFEM.jl
`find` will soon return cartesian indices (https://github.com/JuliaLang/julia/pull/24774), so this benchmark needs to convert them to linear indices. Unfortunately, `LinearIndices` currently does not allow indexing with an array, so we need to use `map`.
=> Prepare SparseFEM benchmark to changes to find() on Julia master

src/array/generate_kernel.jl, src/array/generate_loops.jl, src/array/subarray.jl, src/array/sumindex.jl, src/collection/CollectionBenchmarks.jl, src/tuple/TupleBenchmarks.jl, src/union/UnionBenchmarks.jl
Not tested locally on 0.6, so let's allow the tests to tell me whether I've broken anything. But Compat seems to have been very well updated (thanks to all who did that) for these changes.
Fixes many, but not all, of the issues #158. The rest might be better handled by others. However, I believe @ararslan mentioned that nanosoldier has been slower because of the warnings; I bet this will get the worst of the slowdowns (any indexing-related deprecations are usually fatal for performance).
=> Fix numerous deprecation warnings

src/linalg/LinAlgBenchmarks.jl, src/parallel/ThreadedStockCorr.jl, src/sparse/SparseBenchmarks.jl
Sort some warnings related to the `A[ct]_(mul|ldiv|rdiv)_B[ct][!]` deprecation. Ref. https://github.com/JuliaCI/BaseBenchmarks.jl/issues/158#issuecomment-357084917. Best!
=> adapt to the post-jazz world

src/array/ArrayBenchmarks.jl, src/array/generate_kernel.jl, src/misc/MiscellaneousBenchmarks.jl, src/problem/JSONParse.jl, src/problem/SpellCheck.jl, src/shootout/ShootoutBenchmarks.jl, src/shootout/regex_dna.jl, src/string/StringBenchmarks.jl
This tackles `replace` without `Pair`s, `parse(::String)`, and another instance of global variable overwriting. Ref #158.
=> Fix some 0.7 deprecations

src/find/FindBenchmarks.jl
This should let BaseBenchmarks run successfully on newest master.
=> Fix `find` benchmarks for `nothing` sentinel

src/union/UnionBenchmarks.jl
Add benchmarks comparing a simple loop with `map` and `broadcast`. Use `missing` instead of `nothing` since it propagates with standard operations, which allows testing more cases.
These are the benchmarks associated with https://github.com/JuliaLang/julia/pull/25828.
=> Add benchmarks for map and broadcast with Union{T, Missing} arrays

src/find/FindBenchmarks.jl
The benchmarks did not actually test `Vector{Bool}` for the 80/20 and 20/80 cases since `.>` and `.<` return `BitVector`s.
Noticed while checking results at https://github.com/JuliaLang/julia/pull/25879#issuecomment-363419635.
=> Fix using Vector{Bool} instead of BitVector in find benchmarks

src/array/ArrayBenchmarks.jl, src/array/subarray.jl, src/array/sumindex.jl, src/misc/MiscellaneousBenchmarks.jl, src/problem/GoGame.jl, src/problem/Laplacian.jl
When a deprecation appears in the hot loop of a tuned benchmark, BaseBenchmarks basically becomes non-terminating.  So this PR anticipates some of the coming changes in JuliaLang/julia#24368.  I have also taken the opportunity to fix the few other deprecations I ran into -- none of those were in hot loops.
Note that I have significantly changed some of these algorithms in order to better take advantage of dot-fusion.  I think that is in the spirit of those specific benchmarks, but if desired I can happily revert that back to the most-minimal change required to avoid the deprecation.
=> Remove deprecations (and coming deprecations)

src/array/ArrayBenchmarks.jl
For testing https://github.com/JuliaLang/julia/pull/25766
=> add benchmarks for accumulate and cumsum

src/find/FindBenchmarks.jl
Prepare for deprecation of linearindices. This function was not strictly needed here.
See https://github.com/JuliaLang/julia/pull/26775.
=> Stop using linearindices

REQUIRE, src/array/ArrayBenchmarks.jl, src/micro/MicroBenchmarks.jl, src/micro/methods.jl
Instead, condition the `var` benchmark on it being in Base, and rework the use of `std` to compute the standard deviation manually.
This was my bad, we shouldn't have external dependencies in BaseBenchmarks other than Compat and BenchmarkTools.
=> Remove dependency on StatsBase

src/shootout/revcomp.jl
the current implementation hits https://github.com/JuliaLang/julia/issues/15276 so the benchmark doesn't measure what is intended.
=> workaround issue #15276

src/problem/Raytracer.jl
Using `Array` is overly pessimistic.
=> change the objects in group to be stored in a Vector instead of Array

src/problem/SpellCheck.jl
Should fix loading the problem dataset taking forever.
Note that this doesn't change any benchmark, just makes creating the input data set faster.
=> disable UTF check when creating input data

src/simd/SIMDBenchmarks.jl
From https://github.com/JuliaLang/julia/pull/27670 it was discovered that we have differing performance in SIMD-ability based upon aliasing of arrays within a loop. This explicitly tests that. This also explicitly adds tests to track auto-simdification.
=> More thorough SIMD tests

src/collection/CollectionBenchmarks.jl
Adds the new `IdDict` to the collection benchmarks, x-ref: https://github.com/JuliaLang/julia/pull/25210
IdDict is missing the `pop!(iddict)` method, thus a few more guards.  Probably this method should be added to `IdDict`.
TODO: this should probably be made compatible with older Julia versions.
CC: @rfourquet
=> RFC/WIP: Added IdDict to collection benchmarks

src/union/UnionBenchmarks.jl
Only run on 0.7 since Base.Sort.Defalg treats missing differently from nothing, and missing does not exist on 0.6.
=> Add sort benchmark for Union{T, Missing}

src/array/ArrayBenchmarks.jl, src/array/sumindex.jl
Should fix deprecations that caused degradations in https://github.com/JuliaLang/julia/pull/27711
=> Adapt to new `init` keyword for `reduce` family of functions

src/union/UnionBenchmarks.jl
This should limit spurious results for sum. It also reflects better typical use cases (data frame columns with missing values in large datasets).
=> Use bigger vector for Union benchmarks

src/array/ArrayBenchmarks.jl, src/array/cat.jl, src/io/IOBenchmarks.jl, src/misc/MiscellaneousBenchmarks.jl, src/scalar/ScalarBenchmarks.jl, src/tuple/TupleBenchmarks.jl
This adds some regression tests from Base for issues that are marked "benchmarks needed".
https://github.com/JuliaLang/julia/issues/4467
https://github.com/JuliaLang/julia/issues/11899
https://github.com/JuliaLang/julia/issues/12165
https://github.com/JuliaLang/julia/issues/13786
https://github.com/JuliaLang/julia/issues/18129
https://github.com/JuliaLang/julia/issues/20517
https://github.com/JuliaLang/julia/issues/21109
https://github.com/JuliaLang/julia/issues/23042
=> add some regression tests from base

src/array/ArrayBenchmarks.jl, src/array/subarray.jl
As suggested in https://discourse.julialang.org/t/avoiding-memory-allocation-for-vector-operations/12447/2?u=jdrugo
adding Gram-Schmidt orthonormalization that uses views for matrix slices
to test speed/allocation of these slices.
=> Add Gram-Schmidt orthonormalization to test view speed

src/misc/MiscellaneousBenchmarks.jl
Adds the benchmarks I've been running repeatedly in https://github.com/JuliaLang/julia/pull/29238.
=> Add benchmarks for collecting zip iterators

src/broadcast/BroadcastBenchmarks.jl, src/linalg/LinAlgBenchmarks.jl, src/misc/MiscellaneousBenchmarks.jl, src/sparse/SparseBenchmarks.jl, src/string/StringBenchmarks.jl
Add regression tests for the following issues / PRs with the benchmark label
https://github.com/JuliaLang/julia/pull/26942
https://github.com/JuliaLang/julia/pull/22462
https://github.com/JuliaLang/julia/pull/29116
https://github.com/JuliaLang/julia/issues/28226
https://github.com/JuliaLang/julia/issues/22275
https://github.com/JuliaLang/julia/pull/21829
https://github.com/JuliaLang/julia/issues/21058
=> add more regression benchmark tests

src/problem/SpellCheck.jl
Using AbstractString here doesn't make sense here.
=> use String instead of AbstractString in SpellCheck benchmark.

src/misc/MiscellaneousBenchmarks.jl
I think I do not understand the concept of `addgroup!` correctly, help welcome. In any case, these Benchmarks would be useful with https://github.com/JuliaLang/julia/pull/29786 in mind.
=> WIP: Benchmark flatten

src/union/UnionBenchmarks.jl
Cover both `T`, `Union{T,Missing}` without missing values and `Union{T,Missing}` with missing values.
=> Improve Union benchmarks

src/array/ArrayBenchmarks.jl
Speeds up the benchmark run by removing unrelated work from benchmark loop. 
Before this commit, it was incorrectly including the `samerand()` calculation as part of the array growth benchmark.
I don't actually know the right way to list the performance improvements, but I did it like this:
```julia
julia> improvements = regressions(judge(minimum(master), minimum(pr))); # Reversed master & pr to print improvements
julia> pairs = leaves(improvements) # an array of (ID, `TrialJudgement`) pairs
3-element Array{Any,1}:
(Any["(\"push_single!\", 2048)"], TrialJudgement(+738.94% => regression))
(Any["(\"push_single!\", 256)"], TrialJudgement(+2911.24% => regression))
(Any["(\"push_single!\", 8)"], TrialJudgement(+7394.20% => regression))
```
=> Fix Array growth benchmark: interpolate `samerand()` instead of calculating inside benchmark loop

src/linalg/LinAlgBenchmarks.jl
For tracking e.g. https://github.com/JuliaLang/julia/issues/34013: the matrix product of 2x2 and 3x3 matrices are done in julia rather than dispatched to BLAS for performance.
=> add test for 3- and 5-arg mul! with 2x2 and 3x3 matrices product

src/misc/MiscellaneousBenchmarks.jl
This patch adds benchmarks for code improved by transducers https://github.com/JuliaLang/julia/pull/33526
=> Add benchmarks for foldl on iterators

src/find/FindBenchmarks.jl
Test with changing proportion of `true` values, which affects speed a lot due notably to the cost of pushing new elements and/or reallocating the result.
Useful to benchmark https://github.com/JuliaLang/julia/pull/37177.
=> Add more findall benchmarks

src/string/StringBenchmarks.jl
String equality got a performance boost in https://github.com/JuliaLang/julia/pull/37192#issuecomment-687390486 and I wanted to make we don't see a regression in the future.
=> Add benchmarks for `==(::AbstractString, ::AbstractString)`

.github/workflows/retune.yml
The process is like this:
- cron job on nanosoldier6 runs the retuning script, then pushes the new `params.json` to a branch called `retune`
- this workflow picks up that push and opens a PR from `retune` to `master`
=> Add workflow to open retuning PRs automatically

src/simd/SIMDBenchmarks.jl
Some original perf-test functions are extended to bench 2/3/4d Cartesian simd.
Since the length of 1st dim definitely influence the performace, I‘m not confident with the representativeness of choosed bench size.
Pinging @chriselrod for advice.
see also https://github.com/JuliaLang/julia/pull/42736
=> Add Cartesian related simd benchmarks

src/inference/InferenceBenchmarks.jl
The nanosoldier seems to unify the subgroup names otherwise somehow like:
["inference", "abstract interpretation"]
["inference"]
["inference", "optimization"]
This change circumvents it and also makes the subgroup meaning more explicit:
["inference", "abstract interpretation"]
["inference", "allinference"]
["inference", "optimization"]
=> rename `["inference", "inference"]` subgroup to `["inference", "allinference"]`

src/inference/InferenceBenchmarks.jl
This benchmark target corresponds to JuliaLang/julia/pull/46535.
`method_match_cache` contains many artificially generated broadcasting
operations, that will lead to constant propagations and accompanying
method match analysis on call sites with same abstract signatures, e.g.
- `Tuple{typeof(convert), Type{Int64}, Int64}`
- `Tuple{typeof(convert), Type{Float64}, Float64}`
Since we currently don't cache method match result for abstract call
signatures on the level of the runtime system, we can obtain the best
performance if we cache such abstract method match results on Julia level,
that will be revived by JuliaLang/julia/pull/46535.
=> inference: add benchmark target to check benefit of method match cache

src/inference/InferenceBenchmarks.jl
These cases are very fragile and don't necessarily reflect the inference performance directly.
=> inference: remove benchmark cases that target inference routines themselves

src/sort/SortBenchmarks.jl
Greatly increase the diversity of benchmarks while reducing runtime to 0.6x of what it was before
I crafted these benchmarks for personal experience, from building off of the benchmarks I used in #47383, and from searching [everything that is tagged with both sort and performance](https://github.com/JuliaLang/julia/issues?q=label%3Asort+label%3Aperformance). I kept most of the existing benchmarks, but reduced their redundancy significantly.
Something had to be lost in this change and what was lost is primarily tests of sorting large arrays that are already sorted, reverse sorted or all same with specified non-default algorithms.
=> rewrite SortBenchmarks.jl

src/array/ArrayBenchmarks.jl, src/array/sumindex.jl, src/io/IOBenchmarks.jl, src/misc/MiscellaneousBenchmarks.jl, src/sort/SortBenchmarks.jl, src/sparse/SparseBenchmarks.jl
This fixes all of Sparse, IO, Array, and Misc to save about 2 GB for a 1000x improvement on those
```
julia> varinfo(BaseBenchmarks, all=true, sortby=:size)
name                           size summary                                               
––––––––––––––––––––––– ––––––––––– ––––––––––––––––––––––––––––––––––––––––––––––––––––––
BaseBenchmarks          272.275 MiB Module                                                
SUITE                   265.295 MiB 23-element BenchmarkGroup([])                         
LinAlgBenchmarks        216.710 MiB Module                                                
BroadcastBenchmarks      30.804 MiB Module                                                
UnionBenchmarks           8.505 MiB Module …
```
=> save several GB of memory on just load

src/inference/InferenceBenchmarks.jl
Looks like we require 1.10+ now -- https://github.com/JuliaCI/BaseBenchmarks.jl/pull/328.
=> update comment in InferenceBenchmarks to reflect that it requires 1.10+
